### PR TITLE
Unique Names for Regex Patterns

### PR DESCRIPTION
**Pull request by pyieh**
Added a Name field to regex patterns as part of the global configurations and forces them to be unique. Allows for human-readable label of regex patterns and makes Admin remote configuration of these patterns easier.

- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by ramapalani — APPROVED** [review]
LGTM

**Comment by pyieh** [comment]
@oleg-nenashev I'm wondering why the maven-release-plugin didn't cut a new release for the plugin (I had to manually do a release). Looks like there was an error message where the plugin's JAR is missing. Can you take a look and let me know what's missing and needs to be done?

**Comment by pyieh** [comment]
@oleg-nenashev Can we get some help looking into why the `maven-release-plugin` didn't catch this PR's merge to `master` and release the plugin like other PR merges?

**Comment by pyieh** [comment]
@jglick Wondering if we can get some help looking into why the maven-release-plugin didn't catch and do a release for our PR merge and is there a way to force that?

**Comment by jglick** [comment]
> why the maven-release-plugin didn't cut a new release for the plugin (I had to manually do a release)

Not sure I follow the question. Are you asking about https://www.jenkins.io/doc/developer/publishing/releasing-cd/ which you have not set up for this plugin? Human-oriented version numbers (`1.3` etc.) produced manually and on demand via `maven-release-plugin` (running `mvn -B release:prepare release:perform` using personal Artifactory & GitHub credentials) is the traditional way of releasing plugins. Maybe you are asking something unrelated.

> an error message where the plugin's JAR is missing

Which error message?

Better to use the dev list, and be specific.

**Comment by Faheetah** [comment]
This PR broke the plugin functionality, even using the snippet generator from Jenkins throws `java.lang.ClassCastException: java.util.Collections$UnmodifiableMap cannot be cast to java.lang.String`

**Comment by pyieh** [comment]
@Faheetah Can you open a ticket with your specific Jenkins configs? We've been running this version in our production Jenkins since its release with no issues.

**Comment by Faheetah** [comment]
@pyieh someone already has one looks like, but no response to it. Do you have a config publicly viewable somewhere maybe the pipeline builder is wrong but I can't figure out how to make it work. Anyway this can move to the issue, I don't have it off hand but it's one of the most recently created

**Comment by v1v** [comment]
I've just found this is a breaking change, with `3.1` the below snippet worked like a charm

```groovy
wrap([$class: 'MaskPasswordsBuildWrapper', varMaskRegexes: [[regex: 'token:[^,]*']]]) {
  // ...
}
```

but after upgrading to `3.3`, things start failing apart:

```
15:39:59  [ERROR] Exception: java.lang.IllegalArgumentException: Could not instantiate {delegate={$class=MaskPasswordsBuildWrapper, varMaskRegexes=[{regex=token:[^,]*}]}} for org.jenkinsci.plugins.workflow.steps.CoreWrapperStep: java.lang.IllegalArgumentException: Could not instantiate {varMaskRegexes=[{regex=token:[^,]*}]} for com.michelin.cio.hudson.plugins.maskpasswords.MaskPasswordsBuildWrapper: java.lang.IllegalArgumentException: Could not instantiate {name=null, value=null} for com.michelin.cio.hudson.plugins.maskpasswords.MaskPasswordsConfig$VarMaskRegexEntry: java.lang.ClassCastException: com.michelin.cio.hudson.plugins.maskpasswords.MaskPasswordsConfig$VarMaskRegexEntry.value expects class java.lang.String but received class com.michelin.cio.hudson.plugins.maskpasswords.MaskPasswordsBuildWrapper$VarMaskRegex
15:39:59  [Pipeline] error
```

See [this log](https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/job/main/351/console)


And the shared library step -> https://github.com/elastic/apm-pipeline-library/blob/a160e7fff39c0b0368cf63383b86629975ee1905/vars/githubAppToken.groovy#L87

**Comment by petacz** [comment]
Hi @pyieh,

this PR created a new issue https://issues.jenkins.io/browse/JENKINS-68885?jql=project%20%3D%20JENKINS%20AND%20component%20%3D%20mask-passwords-plugin

Do you have any plans to fix it?

Thanks

**Pull request merged**
