### PR TITLE
Fix mask password parameter not working

### PR DESCRIPTION
**Pull request by bpmarinho**
Fix Password parameter not being Masked. This stopped working on 2.9.
Add unit testing, without the bug fixed, the test fails.
Also tested against docker container jenkins version:
* 2.32.2
* 2.19.4
* 1.625.1
* 1.609.3

### CODE REVIEW

**Comment by bpmarinho** [comment]
@oleg-nenashev is it possible to have a 2.10 out soon?

**Comment by bpmarinho** [comment]
@oleg-nenashev what is the release cycle for this plugin? Can I further help to get this into a new release 2.10? Thanks.

**Comment by oleg-nenashev** [comment]
@bpmarinho Since the plugin is looking for the new maintainer, there is no stable cycle. Will try to test & release it today

**Comment by oleg-nenashev** [comment]
I have discovered a couple of issues 1 week ago. Still need to land it

**Comment by bpmarinho** [comment]
Other issues like the one fixed by this pull request?

**Comment by oleg-nenashev** [comment]
Yep. Anyway, this one should be released

**Pull request merged**
